[build]
  command   = "npm install"
  functions = "netlify/functions"
  publish   = "."

[[redirects]]
  from = "/"
  to   = "/login.html"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
